Repository sdercolin/utaformatix3, pull requests merged in 2022-08, with the labels that each got.

#116 Update French texts
  src/main/kotlin/ui/strings/Strings.kt
Labels: localization

#119 Release v3.13
  README.md
  src/main/kotlin/Main.kt
  src/main/kotlin/exception/UnsupportedFileFormatError.kt
  src/main/kotlin/io/Ppsf.kt
  src/main/kotlin/io/VsqLike.kt
  src/main/kotlin/io/Vsqx.kt
  src/main/kotlin/model/LyricsType.kt
  src/main/kotlin/process/NoteShaping.kt
  src/main/kotlin/process/lyrics/Cleanup.kt
  src/main/kotlin/process/lyrics/Conversion.kt
  src/main/kotlin/process/lyrics/FormatSpecifiedPostCleanup.kt
  src/main/kotlin/process/lyrics/LyricsReplacement.kt
  src/main/kotlin/process/pitch/CevioPitchConversion.kt
  src/main/kotlin/process/pitch/OpenUtauPitchConversion.kt
  src/main/kotlin/process/pitch/PitchCalculation.kt
  src/main/kotlin/process/pitch/SynthVPitchConversion.kt
  src/main/kotlin/process/pitch/UtauMode2PitchConversion.kt
  src/main/kotlin/ui/App.kt
  src/main/kotlin/ui/ConfigurationEditor.kt
  src/main/kotlin/ui/EmbeddedPage.kt
  src/main/kotlin/ui/Exporter.kt
  src/main/kotlin/ui/Importer.kt
  src/main/kotlin/ui/LanguageSelector.kt
  src/main/kotlin/ui/OutputFormatSelector.kt
  src/main/kotlin/ui/common/ErrorDialog.kt
  src/main/kotlin/ui/common/FeatureSwitch.kt
  src/main/kotlin/ui/common/MessageBar.kt
  src/main/kotlin/ui/common/Progress.kt
  src/main/kotlin/ui/common/ScopedFC.kt
  src/main/kotlin/ui/common/SubFC.kt
  src/main/kotlin/ui/common/Title.kt
  src/main/kotlin/ui/configuration/LyricsConvertion.kt
  src/main/kotlin/ui/configuration/LyricsReplacement.kt
  src/main/kotlin/ui/configuration/PitchConversion.kt
  src/main/kotlin/ui/configuration/ProjectZoom.kt
  src/main/kotlin/ui/configuration/SlightRestFilling.kt
  src/main/kotlin/ui/strings/Language.kt
  src/main/kotlin/ui/strings/Strings.kt
  src/main/kotlin/util/ChainCall.kt
  src/test/kotlin/process/pitch/LyricsReplacementTest.kt
  webpack.config.d/global.js
  webpack.config.d/resources.js
Labels: release

#121 Add UfData support
  README.md
  build.gradle.kts
  src/main/kotlin/external/Resources.kt
  src/main/kotlin/io/UfData.kt
  src/main/kotlin/io/Vpr.kt
  src/main/kotlin/io/VsqLike.kt
  src/main/kotlin/io/Vsqx.kt
  src/main/kotlin/model/Format.kt
  src/main/kotlin/model/ImportWarning.kt
  src/main/kotlin/model/Note.kt
  src/main/kotlin/model/Pitch.kt
  src/main/kotlin/model/Project.kt
  src/main/kotlin/ui/OutputFormatSelector.kt
  src/main/kotlin/ui/strings/Strings.kt
  src/main/resources/images/ufdata.png
Labels: feature

#122 Release v3.14
  README.md
  build.gradle.kts
  src/main/kotlin/Main.kt
  src/main/kotlin/external/Resources.kt
  src/main/kotlin/io/UfData.kt
  src/main/kotlin/io/Vpr.kt
  src/main/kotlin/io/VsqLike.kt
  src/main/kotlin/io/Vsqx.kt
  src/main/kotlin/model/Format.kt
  src/main/kotlin/model/ImportWarning.kt
  src/main/kotlin/model/Note.kt
  src/main/kotlin/model/Pitch.kt
  src/main/kotlin/model/Project.kt
  src/main/kotlin/ui/OutputFormatSelector.kt
  src/main/kotlin/ui/strings/Strings.kt
  src/main/resources/images/ufdata.png
Labels: release
